### ISSUE TITLE
Compilation fails to find `Python.h`

### ISSUE THREAD

**Issue by ezatterin** [dkriegner/xrayutilities#105]
Hi,

On a fresh python 3.7 environment pip installing `xrayutilities` fails during compilation with the following error:

```bash
In file included from src/gridder2d.c:26:0:
src/gridder.h:34:20: fatal error: Python.h: No such file or directory
#include <Python.h>
                        ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Ideas? Thanks!

**Comment by dkriegner** [comment]
it seems to me you are missing the python dev headers.

See https://github.com/dkriegner/xrayutilities/blob/master/README.md#requirements

for python 3.7 on linux no binary package is available on pypi. thats something which might need fixing. 
Note to myself: try to generate linux packages either on appveyor or travis

**Comment by ezatterin** [comment]
Indeed 

`apt-get install python3.7-dev`

solved it. Thanks!
