### ISSUE TITLE
MCA data in SPEC file

### ISSUE THREAD

**Issue by dschick** [dkriegner/xrayutilities#123]
Hi @dkriegner ,

I encountered a problem in SPEC files which contain MCA data.
For know I am trying to understand the way the MCA data is read.
I noticed that there is no special case for the `@A` marker which should indicate a line of MCA data.

I think the current implementation does not assume a mixture of MCA and usual scalar data, right?

I will draft a PR if I am a bit more into the code.

Best

Daniel

**Comment by dkriegner** [comment]
For sure MCA data worked at some point. but i did not encounter such files
for a long time. of course a PR is always welcome but it would be better to
first explore why it does not work for you.

**Comment by dschick** [comment]
thanks for your promt reply.

As I said, the `@A` marker is not respected while parsing the file.
Also the parsers does not seem to like a mixture of MCA and scalar data it distinguishes like
```
if self.has_mca
    
else
    
````
This is true for setting the column names and the actual data which are eventually converted to the numpy array

**Comment by dschick** [comment]
Hi Dominik, 

I found some time to dive into the MCA problem.
Indeed the current version of `xrayutilities` allows for reading the `MCA` from test SPEC file.

The issue actually arises again from how Sardana is implemnting the `MCA`s vs. SPEC.
So Sardana allows for multiple `MCA`s in one scan as SPEC seems to allow only for one.
In order to allow for multiple `MCA`s Sardana provides an additional identifier `@DET_X` where `X` is an integer and after the identifier the name of the `MCA` is provided.

Since the `@CHANN` identifier is also given just once, it means, that all `MCA`s in the Sardana implementation should have the same lengh (which is actually not checked for). However, for reading the Sardana `MCA`s the `@CHANN` is not really necessary, as there is no line-breaking available as in SPEC and each `MCA` data line in the scan starts with an `@A` which allows to read the `MCA` data line by line.

Moreover the order of scalar and `MCA` data is swapped/flexible in Sardana.

I made a PR which allows for both types of `MCA`s and here is also a [Sardana test file](https://gist.github.com/dschick/cb1cf42c2e4e230467d7fbc3f1e38374#file-sardana_mca-spec)

**Comment by lrlunin** [comment]
Hello,
just encounted this issue in the version 1.7.6

Exception occurs in `ReadData()` method.

**Comment by dkriegner** [comment]
Does the code in #129 fix the issue for you?

**Comment by lrlunin** [comment]
Yes, I could successfully read the data from .spec file.

**Comment by dkriegner** [comment]
Ok, I look into merging the mentioned PR and include it in a release.
