### ISSUE TITLE
Testdata for Mythen Detector

### ISSUE THREAD

**Issue by EDDIDAT** [dkriegner/xrayutilities#163]
Hello,

I came across your tool because in our department we purchased a Mythen2 R 1D detector for our Seifert diffractometer. Since we can't start the installation for a few weeks, I wanted to ask you if it would be possible for you to send me a measurement file of e.g. LaB6 powder (from J. Appl. Cryst. (2015). 48, 613-618) that you recorded with your Mythen detector and Seifert diffractometer. Then I could familiarize myself with your tool (calibrate detector, FuzzyBinning) in advance.

Many thanks for your help.
Best regards,
Daniel

**Comment by dkriegner** [comment]
Dear Daniel,

I have never recorded LaB6 on any Seifert diffractometer.
But there are some LaB6 data in the test data set (those were recorded with a D500 with Mythen detector). 

You can find the test data at https://sourceforge.net/projects/xrayutilities/files/

does this help?

**Comment by EDDIDAT** [comment]
Thank you for your quick answer!

My mistake, it was a Siemens and not a Seifert diffractometer.

I had already looked at the test data. But I would be more interested in the raw data of the Mythen detector, before the gridding took place. Would it be possible to get such a data set (for just this LaB6 measurement)? I would like to understand in detail how this fuzzy gridding works.

**Comment by dkriegner** [comment]
I am sorry these data I have not with me.

The gridding you certainly best understand when you create a 1D test data set or read the code... in the 2D to 1D data conversion for the powder data not only the fuzzy gridding but additional "magic" to obtain the best peak shape (http://scripts.iucr.org/cgi-bin/paper?po5035) should be done. I think it makes sense to understand these two things separately!
