### ISSUE TITLE
Loading .ras Files

### ISSUE THREAD

**Issue by iriscl** [dkriegner/xrayutilities#171]
Hi Dominik,

Thank you for making this great software free and available to the community! I just wanted to ask you for advice with handling .ras Rigaku files, as it's been a while since I've worked in Python. I'm trying to load a file using the .RASFile() function but it keeps generating a key error that I haven't been able to get around. I'll attach a picture of the traceback below. Did I forget to import something that's preventing the file from being read correctly? For context, I'm trying to load reciprocal space maps to eventually get alloy composition.

Thanks in advance for your help!

Best,
Iris
<img width="1025" alt="Screenshot 2023-08-29 at 12 41 45 PM" src="https://github.com/dkriegner/xrayutilities/assets/47226715/dafe136b-c728-489e-9359-3a7dda37ad4f">

**Comment by dkriegner** [comment]
Dear Iris,

from the traceback you sent this looks like it can either be a problem in xrayutilities or a problem with your data file. It could be that you have a different version of the ras file which uses a feature I did not see yet. 
Is it possible you share the data file for me to test it locally?

If you do not want to make it public you can also send me an email (Address in the readme)

cheers

**Comment by iriscl** [comment]
Hi Dominik,

Just sent you an email with the files. Thanks again for the help!

Best,
Iris

**Comment by dkriegner** [comment]
Please test if the change introduced in #172 fixes the issue for you. 
You might want to get the latest version of the code (ready after ~1 hour from now) for this by following the instructions here:
https://sourceforge.net/p/xrayutilities/mailman/message/37188943/

**Comment by iriscl** [comment]
Hi Dominik,

Yes this fixed the issues, thank you so much!
