### ISSUE TITLE
Confusion in documentation

### ISSUE THREAD

**Issue by brussel13** [dkriegner/xrayutilities#190]
I made a mistake interpreting the Experiment class documentation.
I interpreted "into the primary beam direction" as meaning upstream.  
Something like "Look into the light", or "Look into the beam" meaning to look at the source.
Maybe change this to "downstream" or "parallel to"?

Parameters
:
ipdirlist or tuple or array-like
inplane reference direction (ipdir points into the primary beam direction at zero angles)

**Comment by dkriegner** [comment]
Thanks for reporting this. I will look into it. Certainly some more eyes critically looking into these formulations could be beneficial.

**Comment by dkriegner** [comment]
@brussel13 Could you please check the changes in #192? Do they fully address the issue?

**Comment by brussel13** [comment]
Yes, this is very clear now.  I would not have made the same mistake with this documentation.
Thanks
________________________________
