### ISSUE TITLE
Error using xu.io.EDFFile

### ISSUE THREAD

**Issue by EddieSai** [dkriegner/xrayutilities#41]
The mentioned routine gives back an error while it seems to work for other people. I am able to open my .edf images via fabIO however.

I am attaching a .zip with the code and an example image. The error I get is as follows
[xu.io.EDFFile_Error.zip](https://github.com/dkriegner/xrayutilities/files/1130265/xu.io.EDFFile_Error.zip)
:

Traceback (most recent call last):
  File "XRD_evaluation_ID9_DK.py", line 80, in <module>
    qx, qy, qz, gint, gridder = gridmap(imagenr=1, pathname="./Scan_S6_C3/S6_3K_C3_%04d.edf", stepsize=0.5, start_angle=-10., nx=nx, ny=ny, nz=nz)
  File "XRD_evaluation_ID9_DK.py", line 71, in gridmap
    qx, qy, qz, intensity = rawmap(imagenr, pathname, stepsize, start_angle)
  File "XRD_evaluation_ID9_DK.py", line 52, in rawmap
    a = e.data
  File "/usr/local/lib/python2.7/dist-packages/xrayutilities/io/edf.py", line 323, in data
    self._data[i] = self.ReadData(i)
  File "/usr/local/lib/python2.7/dist-packages/xrayutilities/io/edf.py", line 285, in ReadData
    % (fmt_str, len(bindata) / tot_nofp))
IOError: XU.io.EDFFile: data format (H) has different byte-length, from amount of data one expects 1 bytes per entry

**Comment by dkriegner** [comment]
Thanks for reporting this. I can reproduce the problem using the minimal example below (seems to only exist in python2!)

```
import xrayutilities as xu
xu.config.VERBOSITY=xu.config.DEBUG
e = xu.io.EDFFile('./S6_3K_C3_0001.edf')
d = e.data
```

**Comment by dkriegner** [comment]
@EddieSai please check if the latest commit ( d7d01d8 ) fixes the issue also on your end?!

**Comment by EddieSai** [comment]
Works just fine. Thanks a lot!
