### ISSUE TITLE
Fitting XRD data for thin films and superlattices

### ISSUE THREAD

**Issue by SpaceRobo** [dkriegner/xrayutilities#43]
It would be helpful if the kinematical diffraction model could be used to do a rough fit of formatted XRD data for thin films and superlattices in the same way that data for X-ray reflection can be fit. Being able to choose which factors are varied would be helpful as well.

**Comment by dkriegner** [comment]
I agree that such functionality would be helpful. 

A quick fix for one particular model would be to copy the [fit_xrr function](https://github.com/dkriegner/xrayutilities/blob/master/xrayutilities/simpack/fit.py) for the [KinematicalModel](https://github.com/dkriegner/xrayutilities/blob/master/xrayutilities/simpack/models.py#L215). However, in the long run this should be possible not only for the kinematical but also for the other diffraction models. 

As a note to myself: This is most likely best implemented in a way that all the Models become [lmfit](https://lmfit.github.io/lmfit-py/model.html) models and somehow return a list of their parameters which can then be fitted by a generic wrapper around some lmfit minimize function. The layer stack could also be such a model which has its own parameters which can be easily combined with the ones of the model in a [CompositeModel](https://lmfit.github.io/lmfit-py/model.html#composite-models-adding-or-multiplying-models). In this way even the XRR could be fitted using this generic approach.

**Comment by dkriegner** [comment]
> As a note to myself: This is most likely best implemented in a way that all the Models become [lmfit](https://lmfit.github.io/lmfit-py/model.html) models and somehow return a list of their parameters which can then be fitted by a generic wrapper around some lmfit minimize function. The layer stack could also be such a model which has its own parameters which can be easily combined with the ones of the model in a [CompositeModel](https://lmfit.github.io/lmfit-py/model.html#composite-models-adding-or-multiplying-models). In this way even the XRR could be fitted using this generic approach.

Unfortunately I was a bit naive with my comment. [CompositeModel](https://lmfit.github.io/lmfit-py/model.html#composite-models-adding-or-multiplying-models) is not appropriate for this use-case since the parameters of the LayerStack are needed for the XRR/XRD models and can't be separated out.

I can imagine a solution by dynamic generation of the model function used for [lmfit.Model](https://lmfit.github.io/lmfit-py/model.html#lmfit.model.Model), but this seems not a very clean solution.

**Comment by dkriegner** [comment]
The mentioned commits potentially fix this issue.
Testing and documentation updates are still needed. The issue remains open until this is fixed.

**Comment by dkriegner** [comment]
Missing things which need some more work for XRD models to fit using the new approach are:

- [ ] adding structural parameters (which influence the model) to the list of fit parameters
- [ ] select appropriate fit parameters based on the model 
- [ ] rethink how to treat lattice parameter changes for Pseudomorphic stacks: I am afraid one will have to ignore this and fit only the lattice parameters of individual layers independently which might, however, not be what every user naively expects...
- [ ] documentation updates: including an example script

**Comment by dkriegner** [comment]
I consider the main points of this issue fixed. If problems with the implementation arise or specific improvements are needed (see for example issue #65 a separate issue should be opened
