### ISSUE TITLE
the Gridder class should be an abstract class

### ISSUE THREAD

**Issue by dkriegner** [dkriegner/xrayutilities#45]
The [`Gridder`](https://github.com/dkriegner/xrayutilities/blob/master/xrayutilities/gridder.py#L70) class serves as abstraction of all the derived classes Gridder1D, Gridder2D, ...

The class itself however should not be usable since its methods rely on properties which are defined only in the derived classes.

@eugenwintersberger what is the best/pythonic way to solve this?

I see two options:
1) using the [abc](https://docs.python.org/3/library/abc.html) module or
2) defining dummy variable in Gridder to make it run-able, but still its useless.... 

option 2 seems easy, but does not look like the best solution...

**Comment by dkriegner** [comment]
there is a similar issue with [`LayerModel`](https://github.com/dkriegner/xrayutilities/blob/master/xrayutilities/simpack/models.py#L127) which is not usable itself, but serves as a useful abstraction for derived classes

**Comment by eugenwintersberger** [comment]
Hi Dominik. If I understood that correctly there is no way to render a class pure abstract in Python as long as you want to support both, Python 2.7 and Python 3.X. In Python 3.X ABC would be the right way to go.

**Comment by dkriegner** [comment]
I will investigate to which level the abc is usable in python 2.7. I think the goal of this is not to make this 100% clean from programming point of view, but to deliver a reasonable error message to the user when he wants to initialize one of these classes which are not fully functional...

**Comment by dkriegner** [comment]
@eugenwintersberger could you comment on the mentioned commit? from my point of view thats a viable solution for this issue. if you agree i will put a similar code into the other mentioned classes. 

the python2 & 3 compatible code was taken from https://stackoverflow.com/questions/35673474/using-abc-abcmeta-in-a-way-it-is-compatible-both-with-python-2-7-and-python-3-5

**Comment by dkriegner** [comment]
I consider this issue solved for the moment. Once only python3.3+ is considered as target version one could make improvements and use new functionality of the abc module.
