### ISSUE TITLE
'en' keyword not functioning in xu.simpack.PowderModel class

### ISSUE THREAD

**Issue by wholden** [dkriegner/xrayutilities#47]
While trying to change the energy of x-rays for simulating xrd data, I noticed that the pattern wouldn't change by setting the en=(energy, eV) keyword when PowderModel is instantiated.

e.g., looking at the tutorial example 
(https://xrayutilities.sourceforge.io/simulations.html#powder-diffraction-simulations)

`pm = xu.simpack.PowderModel(Fe_powder, Co_powder, I0=100, en=10000)
`
The addition of the 'en' keyword does not affect the output.  After the above line of code, I checked the energy of the PowderDiffraction class that was created:
`in: pm.pdiff[0].energy
out: 8047.8230999999987`

After some digging, I noticed I could override this and set the energy manually by:
` pm.pdiff[0].energy=10000`

However it seemed to me that this keyword should have worked.  I can see that the keyword get's passed down in the source code, but for whatever reason the PowderDiffraction class that comes out still has the Cu Kalpha1 energy.

I made a jupyter notebook showing the bug based on the example from the tutorial.  I couldn't attach it here as a .ipynb so I changed the extension to txt.  I've also attached a PDF of the notebook.
[XrayUtilities_BugDemonstration.pdf](https://github.com/dkriegner/xrayutilities/files/1481099/XrayUtilities_BugDemonstration.pdf)
[XrayUtilities_BugDemonstration.txt](https://github.com/dkriegner/xrayutilities/files/1481100/XrayUtilities_BugDemonstration.txt)

**Comment by wholden** [comment]
I have since understood that perhaps the intended method of controlling this is by setting the [powder.emission] setting in the xrayutilities.conf file.  

I can use it that way, but it seems like the 'en' kwarg was getting passed through and should have worked, and also having the ability to control it through kwargs permits easy comparison of patterns at different incident energies.  I'm also slightly confused since now I see that manually changing the `pm.pdiff[0].energy=10000` doesn't affect the `pm.pdiff[0].settings` attribute, which still contains the value from the conf file.  Not sure what to make of that.

**Comment by dkriegner** [comment]
@wholden: this is indeed a bug/inconvenience in the latest release which was since then fixed. Please look at issue #42 which shows how it can be done and should also work for PowderModel when you use the newest GIT version. I will make an release in the next weeks which will contain this and lots of more improvements
