### ISSUE TITLE
[question] About running tests

### ISSUE THREAD

**Issue by alexmarie78** [dkriegner/xrayutilities#69]
Hello again,
The package is almost done, but I am trying to write debian/tests/control file for CI.
I am wondering how do you run tests in the python-xrayutilities/tests ?
Do you run them one by one or is it possible to run them all with one command?
Cheers,
Alex

**Comment by dkriegner** [comment]
python setup.py test

Is one option to run all. 

python -m unittest2 discover 

Might also work. There might be a difference in which location is used for the import of xrayutilities. The setup.py method was modified by @eugenwintersberger specifically for the debian tests to he run before the package is installed. So i guess this is the beat method for you.

**Comment by alexmarie78** [comment]
Thanks for your response, I'll use python setup.py test then.
