### ISSUE TITLE
[Bug] While building xrayutilities 

### ISSUE THREAD

**Issue by alexmarie78** [dkriegner/xrayutilities#78]
Hello, 
I am trying to package xrayutilities into Debian.
The build seems to work fine.
However, during the Lintian tests, there is a source-is-missing tag cause by this file : 
```
E: python-xrayutilities source: source-is-missing examples/__pycache__/rigaku_helper.cpython-36.pyc

E: Lintian run failed (policy violation)
```

I tried to remove it by override the auto_clean in debian/rules : 
```
override_dh_auto_clean:
	rm -rf build
	rm -rf examples/__pycache__
```

But I got the same error after another build.
Do you have any ideas of what is missing or what could prevent this error ?

Thanks in advance for your answer,

Alexandre Marie

**Comment by dkriegner** [comment]
b89f478 could potentially fix this issue.

Clearly i did not clean up my local dev directory before i packaged xrayutilities and the MANIFEST.in file had a too aggressive recursive include statement. I hope it is fixed by the mentioned commit. I suggest you pull master and create a new source distribution from it for your testing and let me know if that fixes the issue.

**Comment by alexmarie78** [comment]
Hello again,

thanks for your answer. 
The issue is that I can't package it if it is not a new release.
If I pull this commit, I'll have the file that makes the build fail twice.
Is it possible for you to do a release with last commit ?

Cheers,

Alexandre Marie

**Comment by dkriegner** [comment]
Hi Alexandre,

It seems a bit odd to make a full release just that you can test your
packaging scripts/tests...
It would be important to know that the issue with the packaging is indeed
fixed before making a release.

A release tarball is easily generated by

python setup.py sdist

which is exactly what I would do when making a release! Can't you do that
locally?

cheers
dominik

**Comment by dkriegner** [comment]
@alexmarie78 please revisit this issue after the release of 1.5.3

**Comment by dkriegner** [comment]
@alexmarie78 given your progress seen in issue #89 I assume this issue can be closed
