### ISSUE TITLE
Trouble installing the package with python 2.7 on MacOS 10.14.5

### ISSUE THREAD

**Issue by yang15** [dkriegner/xrayutilities#80]
I tried both with and without openmp with python 2.7 and gcc-8, plus I have openmp installed and tested. The building process failed at linking the object files. The error is shown below:

gcc -bundle -undefined dynamic_lookup -L/Users/jing/anaconda3/envs/molSimplify2019/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.6-x86_64-2.7/xrayutilities/src/cxrayutilities.o build/temp.macosx-10.6-x86_64-2.7/xrayutilities/src/block_average.o build/temp.macosx-10.6-x86_64-2.7/xrayutilities/src/gridder1d.o build/temp.macosx-10.6-x86_64-2.7/xrayutilities/src/file_io.o build/temp.macosx-10.6-x86_64-2.7/xrayutilities/src/gridder2d.o build/temp.macosx-10.6-x86_64-2.7/xrayutilities/src/gridder3d.o build/temp.macosx-10.6-x86_64-2.7/xrayutilities/src/gridder_utils.o build/temp.macosx-10.6-x86_64-2.7/xrayutilities/src/qconversion.o -L/Users/jing/anaconda3/envs/molSimplify2019/lib -o build/lib.macosx-10.6-x86_64-2.7/xrayutilities/cxrayutilities.so
Error: cannot find ld for x86_64 in /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../libexec/ld/ppc /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../libexec/ld/ppc /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../libexec/ld/ppc or /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../libexec/ld/ppc
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

Any ideas on how to fix this error?

**Comment by dkriegner** [comment]
It seems to me this error is unrelated to xrayutilities. Somehow your build tools are not working correctly/incomplete. 

Why are you using gcc? I thought clang is the default compiler on osx?

**Comment by yang15** [comment]
I did not make any extra settings. It seems that setup.py figured out the settings on its own. Is there any way I can change the compiler settings? I happened to figure out that I have to add sudo in front of the linking command, but sudo python setup.py install seems not applying sudo to this command. Is there a way I can tediously put sudo in front of each of the gcc command?

**Comment by dkriegner** [comment]
xrayutilities/setup.py doesn't do anything special to select a particular compiler... thats all left to setuptools which on your system seems to be supplied by anaconda. That being said xrayutlities can't do anything to change the commands called during the build process. I never heard that admin-rights would be needed for the building. Of course you can promote your user to root rights and give it a try (e.g. sudo su https://superuser.com/questions/592323/how-do-i-become-root-on-mac-os-x/592324).

**Comment by dkriegner** [comment]
I am tempted to close this issue since it seems to be unrelated to xrayutilities. I will keep it open for some more time in the hope that maybe other MacOS users can give useful hints for the reporter!

@yang15 if you fix the issue let us know

**Comment by dkriegner** [comment]
related to build tools and not to xrayutilities. Closing
