### ISSUE TITLE
Please release a new stable version, because xrayutilities is great!

### ISSUE THREAD

**Issue by leycec** [dkriegner/xrayutilities#86]
Thanks for all the excellent volunteerism, @dkrieger. `xrayutilities` rocks the open-source Cashbah.

There have been a number of critical bug fixes since the last stable 1.5.2 release –including #76. Of course, I just hit #76 several minutes ago in attempting to replicate the Jupyter Notebook code bundled with a popular 2017 blog post: [*Simulating powder x-ray diffraction in Python with Pymatgen and Xrayutilities.*](https://compmatsci.org/2017/04/19/simulating-powder-x-ray-diffraction-with-pymatgen-and-xrayutilities-in-python) `</shakes_fist_silently_at_the_leaden_sky>`

No dramatic biggie, though. Since the live repository's already patched up, we'll just reinstall  `xrayutilities` from `git` and proceed with scientific business as usual. Thanks again! Canadian maple syrup-laden pancakes for all. :pancakes: :pancakes: :pancakes:

**Comment by dkriegner** [comment]
I'll consider your request. Its true that many small but important things were fixed after 1.5.2
