### ISSUE TITLE
Error with Matplotlib inline backend in FitModel.fit

### ISSUE THREAD

**Issue by aaaaa774** [dkriegner/xrayutilities#87]
Hi, when I was running the file simpack_xrr_SiO2_Ru_CoFe_IrMn_Al2O3.py, I got the problem:
ValueError: Axes instance argument was not found in a figure
![1](https://user-images.githubusercontent.com/56179632/66263543-8dc9e000-e7c2-11e9-8c46-2e91758f4857.png)
![2](https://user-images.githubusercontent.com/56179632/66263544-915d6700-e7c2-11e9-890b-5714e40012eb.png)
![3](https://user-images.githubusercontent.com/56179632/66263545-93272a80-e7c2-11e9-87f3-c3036f09ee5e.png)

**Comment by dkriegner** [comment]
I think the problem you describe is somehow related to the use of the matplotlib inline backend. 
If you need to use this backend (or another one with the same limitation) you will have to disable the plot functionality (line 47 in the example script). 

If you use a different backend it should work. 

I try to find a way to detect this limitation and prevent the appearance of the error.

**Comment by dkriegner** [comment]
The mentioned commit should fix the error you hit. I cleaned up the corresponding code and in my tests it now works using different matplotlib backends. The behavior is not exactly the same. For the inline backend (which somehow after calling show closes the figure) the FitModel.fit function (with plot and verbose True) will create a plot at the beginning of the fit with the initial parameters curve and experimental data and another one at the end containing data, initial and fitted curves. For interactive backends the fitted line is updated during the fitting continously.
