### ISSUE TITLE
[Build] python-xrayutilities

### ISSUE THREAD

**Issue by alexmarie78** [dkriegner/xrayutilities#92]
Hello again,

I saw this message while building the package before pushing it to Debian.
I wanted to ask you what should I do about that, if there is something to do or not.

_____________________________________________________________
[[2169,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: diffabs6

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------

**Comment by dkriegner** [comment]
What has that to do with xrayutilities? what you call when you see this message?
xrayutilities does not use MPI...

**Comment by dkriegner** [comment]
closing since it seems totally unrelated to xrayutilities. please reopen with more details if needed.
