### ISSUE TITLE
setup.py imports numpy (pip install error)

### ISSUE THREAD

**Issue by ceeli** [dkriegner/xrayutilities#95]
Hello I've noticed on a fresh virtual machine that you can't install xrayutilities without installing numpy manually first. That is because numpy is imported in setup.py which must be imported to fetch the dependencies in the first place. I looked at it and it seems that numpy isn't used in setup.py. I think just removing the import should solve the issue.

**Comment by dkriegner** [comment]
Unfortunately numpy is needed in setup.py. it can't be removed. Using pip
numpy should be fetched before setup.py is imported.

Can you explain the commands you used?

I maybe need to change the documentation to only showcase the use of pip.

**Comment by ceeli** [comment]
Oh I didn't notice that you need the header files of numpy, sorry.

I never had any troubles actually installing the package, I just noticed the sub optimal behavior when numpy is not installed, but I guess there is no good solution to that. Thanks for the fast answer though :)

**Comment by dkriegner** [comment]
reopening until documentation is fixed to show only pip usage (or add an appropriate note for the user of setup.py)
